title: Your awesome title
email: your-email@domain.com
description: En https://repararaireacondicionadovalencia.com/puig/ buscamos iniciar una acta pequeña contigo y nuestra asistencia en mantenimiento de aire acondicionado Puig, para que te quedes con el mejor grupo de atención

baseurl: "/"
url: http://keralahost.in/mariogomez
google_adsense: Your-adsense-code

markdown: kramdown

name: Your awesome title

date: 2019-04-23 19:28:02 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://keralahost.in/mariogomez/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: 
author_image: 

author: mariogomez
